### PR TITLE
App now works for build 37 or 38 input vcfs.

### PR DESCRIPTION
**Pull request by mattgarner**
Auto-detects the reference build from vcf header and proceeds accordingly

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17)* status: all files reviewed, 5 unresolved discussions (waiting on @mattgarner)

___
*[src/eggd_nirvana_v2.0.10.sh, line 93 at r1](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17#-MSYDKenEdBBqifGuLhT:-MSYDKenEdBBqifGuLhU:b3ddkxa) ([raw file](https://github.com/eastgenomics/eggd_nirvana/blob/cf7be580fe9144d76e764081d6f771c7cafa0871/src/eggd_nirvana_v2.0.10.sh#L93)):*
> ```Shell
>     # Unknown/ambiguous
>     else
>         echo "Unable to unambiguously determine reference genome (37/38) from input vcf header"
> ```

did the exit not work, does it stop properly
___
*[src/eggd_nirvana_v2.0.10.sh, line 99 at r1](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17#-MSYDhT56VOLcAq8IIWD:-MSYDhT61CF-6NGt4B45:bvnaq1v) ([raw file](https://github.com/eastgenomics/eggd_nirvana/blob/cf7be580fe9144d76e764081d6f771c7cafa0871/src/eggd_nirvana_v2.0.10.sh#L99)):*
> ```Shell
> 
>     # Download data
>     NIRVANA_DATA_DIR=$NIRVANA_ROOT/Data
> ```

I'd add {} around the variable there just to be sure
___
*[src/eggd_nirvana_v2.0.10.sh, line 109 at r1](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17#-MSYDp_40zi_4-YzhHDv:-MSYDp_58poMuw0pamyd:b-qx09dc) ([raw file](https://github.com/eastgenomics/eggd_nirvana/blob/cf7be580fe9144d76e764081d6f771c7cafa0871/src/eggd_nirvana_v2.0.10.sh#L109)):*
> ```Shell
>     # Unpack it to the expected dirs
>     echo "Unpacking data"
>     NIRVANA_CACHE_DIR=$NIRVANA_DATA_DIR/Cache
> ```

also there
___
*[src/eggd_nirvana_v2.0.10.sh, line 115 at r1](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17#-MSYDqaX4H-u-pIbODN1:-MSYDqaY5Ga0W20MjB6b:b-qx09dc) ([raw file](https://github.com/eastgenomics/eggd_nirvana/blob/cf7be580fe9144d76e764081d6f771c7cafa0871/src/eggd_nirvana_v2.0.10.sh#L115)):*
> ```Shell
>     mkdir -p $NIRVANA_CACHE_DIR $NIRVANA_REF_DIR $NIRVANA_SUPP_DIR
> 
>     tar xzf $NIRVANA_DATA_DIR/v26.tar.gz -C $NIRVANA_DATA_DIR
> ```

also there
___
*[src/eggd_nirvana_v2.0.10.sh, line 126 at r1](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17#-MSYER2zDd2Vxsz664Q6:-MSYER2zDd2Vxsz664Q7:b-qx09dc) ([raw file](https://github.com/eastgenomics/eggd_nirvana/blob/cf7be580fe9144d76e764081d6f771c7cafa0871/src/eggd_nirvana_v2.0.10.sh#L126)):*
> ```Shell
>     # Set reference genome and build links to data resources
>     REFERENCE_BUILD=GRCh${ref_genome}
>     NIRVANA_CACHE=$NIRVANA_DATA_DIR/Cache/26/$REFERENCE_BUILD/Both  # Numbers here will need to be tweaked if Nirvana version changes
> ```

also there

**Review by mattgarner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17)* status: all files reviewed, 5 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[src/eggd_nirvana_v2.0.10.sh, line 93 at r1](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17#-MSYDKenEdBBqifGuLhT:-MSYILMK6pWYTujJ2r8c:b-ga6nt0) ([raw file](https://github.com/eastgenomics/eggd_nirvana/blob/cf7be580fe9144d76e764081d6f771c7cafa0871/src/eggd_nirvana_v2.0.10.sh#L93)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

did the exit not work, does it stop properly
</blockquote></details>

`exit(1)` doesn't work unfortunately. If the reference is not 37 or 38, it stops as follows:
```
Unable to unambiguously determine reference genome (37/38) from input vcf header
Input vcf reference build: 
Downloading data
Error:  is neither a file nor a folder name
```
So yes, it errors out with a reason for doing so recorded in the logs
___
*[src/eggd_nirvana_v2.0.10.sh, line 99 at r1](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17#-MSYDhT56VOLcAq8IIWD:-MSYIzs3CCqUaM8pCxVB:bll8mxr) ([raw file](https://github.com/eastgenomics/eggd_nirvana/blob/cf7be580fe9144d76e764081d6f771c7cafa0871/src/eggd_nirvana_v2.0.10.sh#L99)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

I'd add {} around the variable there just to be sure
</blockquote></details>

If you agree then I will add this as an issue to be addressed in the next release. 

There's a very small number of possible strings(dx ids) used to populate these variables and these have all been tested successfully, so it should be impossible for this to cause any issues in this case, but I certainly agree that it's generally good practice to {} variable names

**Review by mattgarner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17)* status: all files reviewed, 5 unresolved discussions (waiting on @Yu-jinKim)

___
*[src/eggd_nirvana_v2.0.10.sh, line 109 at r1](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17#-MSYDp_40zi_4-YzhHDv:-MSYO35E0237iovXhmbK:b-9chp70) ([raw file](https://github.com/eastgenomics/eggd_nirvana/blob/cf7be580fe9144d76e764081d6f771c7cafa0871/src/eggd_nirvana_v2.0.10.sh#L109)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

also there
</blockquote></details>

as above
___
*[src/eggd_nirvana_v2.0.10.sh, line 115 at r1](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17#-MSYDqaX4H-u-pIbODN1:-MSYO4b31yVxUJpDfSMN:b-9chp70) ([raw file](https://github.com/eastgenomics/eggd_nirvana/blob/cf7be580fe9144d76e764081d6f771c7cafa0871/src/eggd_nirvana_v2.0.10.sh#L115)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

also there
</blockquote></details>

as above
___
*[src/eggd_nirvana_v2.0.10.sh, line 126 at r1](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17#-MSYER2zDd2Vxsz664Q6:-MSYO5Fq6tXQPFZNkxlC:b-9chp70) ([raw file](https://github.com/eastgenomics/eggd_nirvana/blob/cf7be580fe9144d76e764081d6f771c7cafa0871/src/eggd_nirvana_v2.0.10.sh#L126)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

also there
</blockquote></details>

as above

**Review by Yu-jinKim — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_nirvana/17)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
